nunit/docs

README.md
Fixes #212 
This is just for the readme. The wiki pages have already been removed.
=> Remove Developer FAQ

docs/articles/developer-info/Packaging-the-Console-and-Engine.md, docs/articles/developer-info/Packaging-the-Framework.md, docs/articles/nunit/extending-nunit/Custom-Constraints.md, docs/articles/nunit/extending-nunit/Engine-Extensibility.md, docs/articles/nunit/extending-nunit/Writing-Engine-Extensions.md, docs/articles/nunit/running-tests/NUnitLite-Runner.md, docs/articles/nunit/technical-notes/nunit-internals/specs/Engine-Addins-Spec.md, docs/articles/nunit/writing-tests/TestContext.md, docs/articles/nunit/writing-tests/Warnings.md, docs/articles/nunit/writing-tests/assertions/assertion-models/classic.md, docs/articles/nunit/writing-tests/assertions/assertion-models/constraint.md, docs/articles/nunit/writing-tests/attributes/levelofparallelism.md, docs/articles/nunit/writing-tests/attributes/nontestassembly.md, docs/articles/nunit/writing-tests/attributes/testcasesource.md, docs/articles/nunit/writing-tests/attributes/testfixture.md, docs/articles/nunit/writing-tests/constraints/NullConstraint.md, docs/articles/nunit/writing-tests/constraints/ReusableConstraint.md
=> Code sample alignment

docs/articles/nunit/extending-nunit/Engine-Extensibility.md, docs/articles/nunit/extending-nunit/Writing-Engine-Extensions.md, docs/articles/nunit/running-tests/toc.yml
I just build the new docfx site for the first time - it looks brilliant! 😄  Here's some miscellaneous fixes I spotted along the way.
=> Misc formatting fixes

docs/articles/developer-info/Coding-Standards.md, docs/articles/nunit/extending-nunit/Custom-Constraints.md, docs/articles/nunit/extending-nunit/Event-Listeners.md, docs/articles/nunit/extending-nunit/Framework-Drivers.md, docs/articles/nunit/extending-nunit/IApplyToTest-Interface.md, docs/articles/nunit/extending-nunit/Project-Loaders.md, docs/articles/nunit/extending-nunit/Result-Writers.md, docs/articles/nunit/extending-nunit/Writing-Engine-Extensions.md, docs/articles/nunit/technical-notes/nunit-internals/specs/Engine-Addins-Spec.md, docs/articles/nunit/technical-notes/nunit-internals/specs/Extended-Constraint-Syntax-Spec.md, docs/articles/nunit/technical-notes/nunit-internals/specs/Internal-Trace-Spec.md, docs/articles/nunit/technical-notes/usage/SetUp-and-TearDown.md, docs/articles/nunit/writing-tests/attributes/maxtime.md, docs/articles/nunit/writing-tests/attributes/order.md, docs/articles/nunit/writing-tests/attributes/range.md, docs/articles/nunit/writing-tests/attributes/requiresthread.md, docs/articles/nunit/writing-tests/attributes/sequential.md, docs/articles/nunit/writing-tests/attributes/testfixture.md, docs/articles/nunit/writing-tests/attributes/testfixturesource.md, docs/articles/nunit/writing-tests/attributes/timeout.md, docs/articles/nunit/writing-tests/attributes/values.md, docs/articles/nunit/writing-tests/constraints/EqualConstraint.md, docs/articles/nunit/writing-tests/setup-teardown/SetUp-and-TearDown-Changes.md, docs/articles/nunit/writing-tests/setup-teardown/index.md
=> Comment elipses in code samples

.github/workflows/build-process.yml
May need to merge this in order to see if it actually kicks things off.
=> GitHub action for building docs

docs/articles/nunit/technical-notes/nunit-internals/NUnit-Internals.md, docs/articles/nunit/technical-notes/nunit-internals/specs/Specifications.md, docs/articles/nunit/writing-tests/attributes/apartment.md, docs/articles/nunit/writing-tests/attributes/combinatorial.md, docs/articles/nunit/writing-tests/attributes/culture.md, docs/articles/nunit/writing-tests/attributes/datapoint.md, docs/articles/nunit/writing-tests/attributes/datapointsource.md, docs/articles/nunit/writing-tests/attributes/levelofparallelism.md, docs/articles/nunit/writing-tests/attributes/nonparallelizable.md, docs/articles/nunit/writing-tests/attributes/onetimesetup.md, docs/articles/nunit/writing-tests/attributes/onetimeteardown.md, docs/articles/nunit/writing-tests/attributes/pairwise.md, docs/articles/nunit/writing-tests/attributes/parallelizable.md, docs/articles/nunit/writing-tests/attributes/random.md, docs/articles/nunit/writing-tests/attributes/range.md, docs/articles/nunit/writing-tests/attributes/requiresthread.md, docs/articles/nunit/writing-tests/attributes/sequential.md, docs/articles/nunit/writing-tests/attributes/setculture.md, docs/articles/nunit/writing-tests/attributes/setuiculture.md, docs/articles/nunit/writing-tests/attributes/setup.md, docs/articles/nunit/writing-tests/attributes/setupfixture.md, docs/articles/nunit/writing-tests/attributes/teardown.md, docs/articles/nunit/writing-tests/attributes/testcase.md, docs/articles/nunit/writing-tests/attributes/testfixturesetup.md, docs/articles/nunit/writing-tests/attributes/testfixtureteardown.md, docs/articles/nunit/writing-tests/attributes/theory.md, docs/articles/nunit/writing-tests/attributes/values.md, docs/articles/vs-test-adapter/toc.yml
Resolves #378.
After this point, there should be no warnings in the docfx build.
=> Fix case-sensitive links

.github/workflows/build-process.yml, docs/articles/nunit/writing-tests/attributes/nonparallelizable.md
=> Enable Warnings as errors (and test an error condition)

README.md
=> Update readme with build process

docs/articles/nunit/extending-nunit/Engine-Extensibility.md, docs/articles/nunit/getting-started/breaking-changes.md, docs/articles/nunit/release-notes/breaking-changes.md, docs/articles/nunit/writing-tests/attributes/onetimesetup.md, docs/articles/nunit/writing-tests/attributes/onetimeteardown.md, docs/articles/nunit/writing-tests/attributes/property.md, docs/articles/nunit/writing-tests/attributes/testcasesource.md
=> Remove wiki-style links

docs/articles/developer-info/Team-Practices.md, docs/articles/nunit-analyzers/NUnit-Analyzers.md, docs/articles/nunit/intro.md, docs/articles/vs-test-generator/Visual-Studio-Test-Generator.md, docs/articles/xamarin-runners/index.md, docs/index.md
=> Wiki links cleanup

.github/workflows/build-process.yml
=> Add spellcheck to build

docs/robots.txt
=> Add robots.txt

.github/workflows/build-process.yml, docs/docfx.json, docs/robots.txt
I had missed this somehow previously; weird timing on a git commit & save I think? 
Part of #397
=> Serve robots.txt file

.github/workflows/build-process.yml
=> Comment the publish action

docs/docfx.json
=> Add title to global metadata

docs/docfx.json
Resolves #407.
> ![full-text-search](https://user-images.githubusercontent.com/2148318/84969408-9c54ef00-b0e6-11ea-8155-773384173e80.gif)
=> Enable the full text search index

docs/docfx.json
=> Add sitemap.xml

docs/articles/nunit/technical-notes/toc.yml, docs/articles/nunit/toc.yml, docs/articles/nunit/writing-tests/assertions/toc.yml, docs/articles/nunit/writing-tests/toc.yml, docs/articles/toc.yml
=> Add topicHref items for child toc.yml entries

docs/articles/nunit/extending-nunit/Custom-Asserts.md, docs/articles/nunit/technical-notes/nunit-internals/Architectural-Overview.md, docs/articles/nunit/technical-notes/nunit-internals/Attribute-Hierarchy.md, docs/articles/nunit/technical-notes/nunit-internals/Framework-Design.md, docs/articles/nunit/technical-notes/nunit-internals/Test-Discovery-And-Execution.md, docs/articles/nunit/technical-notes/nunit-internals/specs/Dynamic-Test-Cases-Spec.md, docs/articles/nunit/technical-notes/nunit-internals/specs/Extended-Constraint-Syntax-Spec.md, docs/articles/nunit/technical-notes/nunit-internals/specs/Include-and-Exclude-Attributes-Spec.md, docs/articles/nunit/technical-notes/nunit-internals/specs/Internal-Trace-Spec.md, docs/articles/nunit/technical-notes/nunit-internals/specs/Test-Dependency-Attribute-Spec.md, docs/articles/nunit/technical-notes/usage/Visual-Studio-Support.md, docs/articles/nunit/technical-notes/usage/XML-Formats.md
=> Use warning visual for drafts

docs/articles/developer-info/toc.yml, docs/articles/nunit-analyzers/toc.yml, docs/articles/nunit/extending-nunit/toc.yml, docs/articles/nunit/running-tests/toc.yml, docs/articles/nunit/technical-notes/nunit-internals/specs/toc.yml, docs/articles/nunit/technical-notes/nunit-internals/toc.yml, docs/articles/nunit/technical-notes/usage/toc.yml, docs/articles/nunit/writing-tests/toc.yml
=> TOC updates to ensure all pages represented

cSpell.json, docs/articles/nunit/running-tests/Console-Command-Line.md, docs/articles/nunit/running-tests/NUnit-Test-Projects.md, docs/articles/nunit/writing-tests/attributes/valuesource.md, docs/articles/toc.yml, docs/articles/vs-test-generator/TestGenerator-Installation.md, docs/articles/vs-test-generator/TestGenerator-Release-Notes-VS2015.md, docs/articles/vs-test-generator/TestGenerator-Release-Notes.md, docs/articles/vs-test-generator/toc.yml, docs/index.md
=> Capture wikis through 6/21

.github/linters/.markdown-lint.yml, .github/workflows/build-process.yml
=> Add super linter (warnings only, no errors)

.github/workflows/build-process.yml, docs/robots.txt
=> Docfx release

.github/workflows/build-process.yml
=> update build process to only validate md

docs/index.md
=> Remove external links from index.md

.github/workflows/build-process.yml
Supports #439 and https://github.com/nunit/nunit.github.io/issues/79
=> Disable publishing

.github/workflows/build-process.yml
After #442 in support of #441, it's time to see if we can get this off the ground. :)
=> Re-enable docs publishing

docs/articles/nunit/extending-nunit/Index.md, docs/articles/nunit/toc.yml
=> Add "Extending NUnit" index page

docs/articles/nunit/running-tests/Index.md, docs/articles/nunit/technical-notes/usage/Assembly-Isolation.md, docs/articles/nunit/technical-notes/usage/Configuration-Files.md, docs/articles/nunit/technical-notes/usage/Runtime-Selection.md, docs/articles/nunit/technical-notes/usage/Visual-Studio-Support.md, docs/articles/nunit/toc.yml
=> Restore "running tests" index page

docs/articles/nunit/writing-tests/attributes/toc.yml
=> Add TOC link for NonParallelizableAttribute

docs/articles/nunit/running-tests/NUnitLite-Options.md, docs/articles/nunit/running-tests/toc.yml
=> Add NUnit Lite Options Page

docs/articles/nunit/writing-tests/attributes/toc.yml
=> Fix TOC reference for TestCaseSource

docs/articles/nunit/technical-notes/usage/Assembly-Isolation.md
=> Fix broken link

.github/workflows/build-process.yml
Shouldn't be able to publish if linting and spellcheck haven't also finished.
=> Add linting and spellcheck to publish

docs/articles/nunit/writing-tests/constraints/RegexConstraint.md
=> RegexConstraint doc update

docs/articles/nunit/release-notes/console-and-engine.md
Release notes updates. I'd like to merge this inline with pushing the release shortly - so reviews welcome! 🙂
=> NUnit Console 3.12 Beta 1 release notes update

docs/articles/nunit/writing-tests/attributes/onetimesetup.md, docs/articles/nunit/writing-tests/attributes/onetimeteardown.md, docs/articles/nunit/writing-tests/attributes/setup.md, docs/articles/nunit/writing-tests/attributes/teardown.md
Resolves #53.
Thanks to @mitchterlisner for reporting some years ago. 😄 We're getting our house in order so I thought I'd finally make these updates.
=> Warnings around inheritance of attributes when hiding base method

docs/articles/nunit/running-tests/Console-Command-Line.md
=> Add notes on --domain=None in Console Command Line

docs/articles/developer-info/toc.yml
This link is broken in the TOC. Is this the correct way to fix it, when a submenu is involved? I'm not totally sure, I'm afraid!
=> Fix Specs menu item

docs/articles/vs-test-adapter/Resources.md
Fixes nunit/nunit3-vs-adapter#788
=> fix(vs-test-adapter): Correct links in Resources.md

.github/ISSUE_TEMPLATE/config.yml
=> Create template for new issues

docs/articles/nunit/writing-tests/attributes/toc.yml
Resolves #536, Follow up to #535.
=> Add FixtureLifeCycle to attribute TOC

docs/custom_template/partials/head.tmpl.partial
Coordinated with @rprouse. Uses the official NUnit account and creates a web property for the docs to track.
=> Add Google Analytics

docs/articles/nunit/running-tests/NUnitLite-Options.md
=> Make documentation up-2-date wrt. help information

docs/articles/nunit/writing-tests/attributes/onetimesetup.md
As spotted in https://github.com/nunit/docs/pull/535#discussion_r555092096
=> Correct typo

cSpell.json, docs/articles/nunit/release-notes/console-and-engine.md
Release notes for NUnit Console 3.12. Currently planning to do the release tomorrow, will take this out of draft status when it's out. 🙂
=> NUnit Console 3.12 release notes

docs/articles/nunit/running-tests/NUnitLite-Options.md
I'm fairly sure this is supported only in the Console. (The docs were originally copies of each other here.)
I can't find anything in the NUnitLite code which supports XSLT's
=> NUnitLite doesn't support XSLT transforms

docs/articles/nunit/running-tests/Test-Selection-Language.md
=> Updated old MSDN links

.devcontainer/Dockerfile, README.md
=> Add npm tooling & docs to Codespaces container

.devcontainer/Dockerfile
We currently use `latest`, but I want to be able to experiment with newer tag versions prior to pinning them to the codespaces VM.
=> [Codespaces] Use specific container tag

.github/workflows/build-process.yml
Pins the build to v1.3.1 of the container in the dockerhub registry, rather than the master branch.
=> Use specific container (from dockerhub) in build

CODE_OF_CONDUCT.md
Resolves #567.
Thanks to @mikkelbu for catching this!
=> Add Code of Conduct Contents

docs/articles/nunit/technical-notes/usage/Test-Result-XML-Format.md
=> fix: Improve documentation of reason element

.devcontainer/devcontainer.json, .tours/codespaces-onboarding.tour
=> Add codespaces extension for tour of project

docs/articles/nunit/writing-tests/attributes/singlethreaded.md
Resolves #52 (IMO, at least for now, as the usage seems straight-forward otherwise)
=> Add minor information to SingleThreaded Attribute

docs/articles/nunit/writing-tests/attributes/repeat.md
Added an example for [Repeate(x)] attribute in docs
=> Add example for repeat attribute

docs/articles/nunit/writing-tests/attributes/random.md
Hi,
This is a proposal to update the `RandomAttribute` documentation to match with the feature added by https://github.com/nunit/nunit/pull/3951.
=> Update RandomAttribute doc to add Guid support

docs/articles/vs-test-adapter/Adapter-Installation.md, docs/articles/vs-test-adapter/Supported-Frameworks.md
See adapter issue https://github.com/nunit/nunit3-vs-adapter/issues/916
=> Adapter issue 916, update installation docs

.github/workflows/build-process.yml
* Adds wkhtmltopdf
* Upgrades from 2.58.2 --> 2.58.9. [(Release Notes)](https://github.com/dotnet/docfx/releases?page=1)
=> Update docfx-action in build process to v1.6.0

.github/workflows/build-process.yml
To see if this will work with a container running .NET 6 rather than .NET Core 3.1
=> Update to docfx-action to v1.7.0

docs/articles/vs-test-adapter/AdapterV4-Release-Notes.md, docs/articles/vs-test-adapter/Tips-And-Tricks.md
=> Fixreleasenotes

docs/styles/main.js
resolve https://github.com/nunit/docs/issues/623
=> Accessibility - add lang to html

docs/docfx.json
resolve https://github.com/nunit/docs/issues/632
=> fix logotype (legacy pages)

docs/css/main.css
resolve https://github.com/nunit/docs/issues/634
=> fix legacy pages on mobile(content container)

docs/css/main.css
resolve https://github.com/nunit/docs/issues/639
=> fix sidebar on mobile (legacy pages)

docs/css/main.css
resolve https://github.com/nunit/docs/issues/641
=> fix footer on mobile (legacy pages)

cSpell.json, docs/articles/developer-info/Packaging-the-Framework.md, docs/articles/nunit/release-notes/framework.md
- Update release notes for the 3.13.3 release
- Updates to the release instructions based on the latest release.
=> Release 3.13.3 release notes

.github/workflows/build-process.yml
=> Update cSpell action to use node 12 --> 18

docs/articles/nunit-engine/release-notes.md
=> Fix build error by using consistent list style

.github/linters/.markdown-lint.yml, .markdownlintrc
=> Disable MD004 rule that mandated bullet point consistency

.github/workflows/build-process.yml
=> Update docfx action to v1.10.0

.github/workflows/build-process.yml
https://github.com/nunit/docfx-action/pull/12
=> Update docfx action to v1.11.0

docs/articles/nunit/writing-tests/attributes/platform.md
see https://github.com/nunit/nunit/pull/4213
=> add Windows11 to platform attributes

docs/articles/nunit/getting-started/dotnet-core-and-dotnet-standard.md, docs/articles/nunit/writing-tests/attributes/setupfixture.md, docs/articles/vs-test-adapter/AdapterV4-Release-Notes.md, docs/articles/vs-test-adapter/Index.md, docs/articles/vs-test-adapter/Supported-Frameworks.md, docs/articles/vs-test-adapter/Tips-And-Tricks.md
Updated documentation for version 4.3.0 of the adapter
=> Adapter430

docs/articles/vs-test-adapter/Supported-Frameworks.md
Based on a quick slack chat with @OsirisTerje
=> Verbiage improvement for Supported-Frameworks.md

.github/dependabot.yml
Another thing to help keep this place fresh & clean. :)
=> Add dependabot for samples file, github actions, and devontainer docker

docs/articles/vs-test-adapter/Adapter-Engine-Compatibility.md
Tiny details related to #715. CC @OsirisTerje as FYI only; just formatting really; nothing wrong.
=> Minor follow up 

.devcontainer/devcontainer.json
Just a little bit of personal joy: for fun, I'm doing this from the devcontainer itself running on my desktop, with the GitHub pull requests extension.
=> Update devcontainer file

.github/workflows/build-process.yml, docs/snippets/Snippets.NUnit/Snippets.NUnit.csproj
=> Use .NET 6 in snippets & build process

docs/articles/nunit/writing-tests/constraints/SubPathConstraint.md
Correct usage of the SubPath constraint and improve examples.
=> Correct usage of the SubPath constraint.

docs/articles/developer-info/The-Teams.md
Resolves #758.
The issue was spacing in the markdown table. 
CC @OsirisTerje.
=> Fix for Emoji display in Team page

.devcontainer/Dockerfile, .github/workflows/build-process.yml
v2.7.0 updates to the latest version of docfx
=> Update docfx-action version

cSpell.json, docs/articles/nunit/release-notes/framework.md
Release notes for NUnit framework version 4 - alpha
=> Releasenunit40alpha1

docs/articles/nunit/writing-tests/attributes/onetimesetup.md
Based on:
- https://github.com/nunit/nunit/issues/4462
=> Use `SetUpFixture` or static contructor to have code only run once

docs/articles/nunit/writing-tests/constraints/BinarySerializableConstraint.md
Note for BinarySerializable.
Resolves #817
=> Note for BinarySerializable

.github/workflows/closed-pr.yml
Helps if the GitHub Action is allowed to take its action. :)
=> Add permissions to the closed PR workflow

.github/workflows/build-process.yml
=> Add PATs to Environment creation steps

.devcontainer/Dockerfile, docs/docfx.json, docs/filterConfig.yml
=> Filter out NUnit.Framework.Internal namespace from published API docs

.github/workflows/build-process.yml
=> Revert artifact upload/download v4 action upgrades

docs/articles/nunit/writing-tests/constraints/EqualConstraint.md
=> Document UsingPropertiesComparer for EqualConstraint

docs/articles/nunit/writing-tests/constraints/GreaterThanConstraint.md, docs/articles/nunit/writing-tests/constraints/GreaterThanOrEqualConstraint.md, docs/articles/nunit/writing-tests/constraints/LessThanConstraint.md, docs/articles/nunit/writing-tests/constraints/LessThanOrEqualConstraint.md
Add documentation for inequality constraints with tolerance
=> Add documentation for inequality constraints with tolerance

docs/articles/nunit/release-notes/framework.md
Updating a link in the release notes as discussed in https://github.com/nunit/docs/pull/906#discussion_r1501851028
=> Update links to docs

docs/articles/nunit/release-notes/framework.md
Fixing NUnit issue https://github.com/nunit/nunit/issues/4610
=> Breakingchanges

docs/articles/nunit/writing-tests/constraints/AnyOfConstraint.md, docs/articles/nunit/writing-tests/constraints/CollectionEquivalentConstraint.md, docs/articles/nunit/writing-tests/constraints/Constraints.md, docs/articles/nunit/writing-tests/constraints/DictionaryContainsKeyConstraint.md, docs/articles/nunit/writing-tests/constraints/DictionaryContainsKeyValuePairConstraint.md, docs/articles/nunit/writing-tests/constraints/EqualConstraint.md, docs/articles/nunit/writing-tests/constraints/SomeItemsConstraint.md, docs/articles/nunit/writing-tests/constraints/UniqueItemsConstraint.md, docs/articles/nunit/writing-tests/constraints/WhiteSpaceConstraint.md, docs/articles/nunit/writing-tests/constraints/toc.yml
Documentation update belonging to: https://github.com/nunit/nunit/pull/4664
=> Document `Is.WhiteSpace` and `IgnoreWhiteSpace`

docs/articles/nunit/writing-tests/attributes/setupfixture.md
This is cosmetics.
I tried to meaningfully complete what seemed an unfinished first sentence.
=> Place explanations about filtering in their note block

docs/articles/nunit-analyzers/NUnit2013.md
Currently broken: https://docs.nunit.org/articles/nunit-analyzers/NUnit2013.html#via-editorconfig-file
=> Close code block on NUnit2013 page

docs/articles/nunit/writing-tests/TestCaseData.md
Fixes https://github.com/nunit/nunit/issues/3359
Adding SetArgDisplayNames documentation on TestCaseData.md
=> Issue-3359 :  Add SetArgDisplayNames documentation on TestCaseData.md

renovate.json
=> Attempt to get regex file path correct for RenvoateBot custom manager

docs/articles/nunit/running-tests/NUnitLite-Runner.md
ref Issue https://github.com/nunit/nunit/issues/4780
=> Adding a paragraph about the startupobject, 

docs/articles/nunit/release-notes/Nunit4.0-MigrationGuide.md
Just catching up with latest changes we made to the script
=> Make editorconfig rule addition slightly more robust

docs/articles/nunit/writing-tests/ListMapper.md
=> Update docs -- do a pass for "Will be removed"

docs/snippets/Snippets.NUnit/Snippets.NUnit.csproj
=> Remove net6.0 target from NUnit snippets project

docs/articles/vs-test-adapter/toc.yml
I previously updated the article in https://github.com/nunit/docs/pull/1018, but noticed now that I forgot to update it in ToC.
=> Update MTP wording in ToC

docs/articles/nunit/writing-tests/attributes/platform.md
This was based on very quick testing using Rider, I don't know if the attribute is actually supported across all test runners.
If i'm wrong about this, feel free to close this PR :smiley:  I just wanted to note it down in case other people were curious.
In case it's not supported across all test runners, maybe that should be noted instead?
=> Add note that [SupportedOSPlatform] is also supported

.github/workflows/build-process.yml
Supports #1045.
While I had high hopes for this, the permissions aspect prevents it from operating as we'd hope.
We'll look to find another way.
=> Remove Netlify preview from PR process
