nunit/docs

docs/articles/developer-info/Issue-Tracking.md
docs/articles/developer-info/Packaging-the-Console-and-Engine.md
docs/articles/developer-info/Packaging-the-Framework.md
docs/articles/developer-info/Packaging-the-V2-Adapter.md
docs/articles/developer-info/Packaging-the-V3-Adapter.md
docs/articles/nunit/getting-started/installation.md
docs/articles/nunit/technical-notes/nunit-internals/specs/Extended-Constraint-Syntax-Spec.md
docs/articles/nunit/technical-notes/usage/XML-Formats.md
docs/articles/vs-test-adapter/Adapter-Release-Notes.md
docs/articles/vs-test-adapter/Tips-And-Tricks.md

Using an old tool I have from a different project, which converts any links to https where possible. 
For ease of review, it ignores anything which redirects, hence why there's still some VS/Google Code links left as http.

Use https for links where possible

---

docs/articles/developer-info/Packaging-the-Console-and-Engine.md
docs/articles/developer-info/Packaging-the-Framework.md
docs/articles/nunit-analyzers/NUnit1013.md
docs/articles/nunit-analyzers/NUnit1014.md
docs/articles/nunit-analyzers/NUnit2007.md
docs/articles/nunit-analyzers/NUnit2008.md
docs/articles/nunit-analyzers/NUnit2009.md
docs/articles/nunit/release-notes/Pre-3.5-Release-Notes.md
docs/articles/nunit/release-notes/framework.md
docs/articles/nunit/technical-notes/nunit-internals/NUnit-3.0-Architecture-(2009).md
docs/articles/vs-test-adapter/Adapter-Release-Notes.md
docs/articles/vs-test-adapter/AdapterV2-Release-Notes.md

Resolves #364.
There actually weren't too many instances of this.

Correct NUnit casing

---

.github/workflows/build-process.yml

No actual code yet; just an echo statement.
Supports #342.
Now we're getting to the fun part! This adds a step to the github actions that should only run for the master branch and not PRs. 
To test it, we're making the step an echo statement for now. It should not run on this PR, and then should run once merged.

Add simple publish step with conditional

---

.github/workflows/build-process.yml

Splits the GitHub actions into four parts:
* Markdown linting
* Spellcheck
* Docfx build
* Publish (which depends on the prior three succeeding in parallel).
Process should now be much more responsive. Faster feedback for the win!

Parallelize the build process

---

docs/index.md

NUnit 2.6.4 was the last release of NUnit V2 made by the NUnit Project. On the original nunit.org documentation page it was shown as "Previous Release" but I don't think it needs to be highlighted that way any longer.
At the same time, I modified the text to clarify that we are talking about Legacy documentation.
@SeanKilleen I'm putting this through the PR process so you can use it as a way to decide what the review requirements for PRs should be for this repo.

Add missing NUnit 2.6.4 link to documentation index page

---

.github/workflows/build-process.yml

Uses our repo, which builds to our container.
Also uses the docfx version 2.561. as of the action version v1.1.0.
Supports #448.

Switch to NUnit's docfx-action

---

.github/workflows/build-process.yml
docs/articles/nunit/intro.md

Supports #466.
We'll check the output from this and see if it makes more sense than super-linter.

Switch to markdownlint-cli

---

.github/workflows/build-process.yml

This started out as an attempt to use html-proofer, but then I realized it would need the artifacts.
So, this PR expanded a little.
It now:
* Splits the build & publish steps into separate steps
* Creates artifacts in the build step
* Uses those artifacts in the publish step
* Also added an html-proofer step that uses the build outputs.
* Runs everything in parallel as much as possible.
Supports #352

Truly parallel builds (from an attempt at html-proofer)

---

docs/articles/nunit/running-tests/Console-Runner.md

Fixes #333.
@SeanKilleen - any ideas how we can make sure this table has sensible column widths? In GitHub's markdown preview it wraps in a bit of an ugly way...maybe docfx will handle it differently?

Document NUnit Console exit codes

---

docs/articles/nunit/extending-nunit/Engine-Extensibility.md

If I'm reading this right, I think this is all the text that's required to document the installation process for an extension / add-in, since `.addins` is already covered in the NUnit engine docs.
Resolves #11. I think.

Update Engine-Extensibility.md to add installation instructions

---

docs/articles/vs-test-adapter/Tips-And-Tricks.md

Referenced this page today, and thought it could do with a better explanation of the patterns used for test naming. 😊

Add Template based test naming info to adapter settings page

---

docs/articles/nunit/writing-tests/TestCaseData.md

I tend to view `nameof` as a step above strings in code for these kinds of things, however I understand this is _close_ to subjective preference. Feelings will not be hurt if this isn't the view of the maintainers, just thought I'd try.
This was a passing observation while reading docs, if there are other places you'd like this to be applied, let me know and I will.
Thank you~!

Use nameof() in docs to reduce magic strings

---

docs/articles/nunit/writing-tests/ListMapper.md
docs/articles/nunit/writing-tests/TestFixtureData.md
docs/articles/nunit/writing-tests/attributes/testcasesource.md
docs/articles/nunit/writing-tests/attributes/testfixturesource.md
docs/articles/nunit/writing-tests/attributes/testof.md

Fixes #523 
This should finish the effort started in #519 .
Please advise if I've missed anything or if anybody feels there is an unjust replacement.
Thank you!

Fixes #523 - finishes applying nameof() to areas where it can replace magic strings

---

.github/issue_template.md

We're now using the github new issue template configuration, which precludes the need for this text in the issue template. 
We may add a template back later, but for now I think this can be removed.

Remove issue_template.md

---

docs/articles/nunit/writing-tests/attributes.md
docs/articles/nunit/writing-tests/attributes/fixturelifecycle.md
docs/articles/nunit/writing-tests/attributes/onetimesetup.md
docs/articles/nunit/writing-tests/attributes/onetimeteardown.md
docs/articles/nunit/writing-tests/attributes/parallelizable.md

Fixes #534
Adds documentation for the new `FixtureLifeCycle` attribute and updates the docs for related attributes.
@jnm2 can you review this for accuracy please?

Adds documentation for the FixtureLifeCycle attribute

---

README.md

Make the badge link to the build process and not to the image

Add link to build process from build badge

---

.github/workflows/build-process.yml

Our build process refers to a published docker image. 
Rather than that, we should be able to use the Dockerfile that is in the GitHub Action's repo itself. 
I think this will avoid needing to publish an image to Docker hub, and allow us to clean up that extraneous DockerHub account etc.

Use GitHub Action rather published docker image

---

docs/articles/nunit/running-tests/NUnitLite-Runner.md

This functionality have not worked for years, and have now been removed in future versions by
https://github.com/nunit/nunit/issues/1428

fix: Remove mention of Program.cs

---

docs/articles/nunit-engine/release-notes.md
docs/articles/nunit-engine/toc.yml
docs/articles/nunit/release-notes/Pre-3.5-Release-Notes.md
docs/articles/nunit/release-notes/toc.yml
docs/articles/vs-test-adapter/AdapterV4-Release-Notes.md

Resolves #609.
Releases notes for console/engine now live under Engine:
> ![image](https://user-images.githubusercontent.com/2148318/145921861-f220864a-e9e9-44be-86a6-64b820e8b04b.png)
Link remains under `NUnit` section.
> ![image](https://user-images.githubusercontent.com/2148318/145921955-7df2a886-ac56-4f7d-979e-4b50e8bef53f.png)
All other links now use a reference to the `uid` that was added for the article in this PR.

Move console release notes

---

LICENSE.md

Resolves #608.
Pinging @rprouse so that he can let me know who should review this to officially approve it before merging. Don't want to merge prematurely because I know license considerations are not trivial things.
I noticed that the [nunit.github.io repo uses the MIT license as well](https://github.com/nunit/nunit.github.io/blob/master/LICENSE).

Add MIT license to docs repo

---

.devcontainer/Dockerfile

Supports #627. 
May resolve it; not sure.
This updates the Dockerfile for our codespaces definition to use the recently created [GitHub Container Registry container for nunit-docfx](https://github.com/nunit/docfx-action/pull/8).

Use dockerfile from GitHub Container Registry

---

docs/articles/nunit/writing-tests/Randomizer-Methods.md

Resolves #629.
Fixes the spellcheck errors in the build.

Use backtick instead of quotes in an article

---

.github/linters/.markdown-lint.yml
.markdownlintrc
docs/articles/nunit/getting-started/dotnet-core-and-dotnet-standard.md

Previously, the linting rule defaulted to ensuring that list items were consistent within a doc.
This makes it explicit in our tooling that asterisks are the standard (as they're in 99% of the docs already).
CC @CharliePoole per our discussion

Standardize linting tooling on asterisk as list style

---

docs/articles/nunit/technical-notes/nunit-internals/specs/Extended-Constraint-Syntax-Spec.md

Small changes to code samples that use smart quotes instead of regular quotes.
This fixes the samples and should allow for a better copy & paste experience.

Do not use smart quotes in code examples

---

cSpell.json

Resolves #682.
This is the recommended way of setting regex patterns for cSpell. Bonus: it allows the file to be valid JSON now.

Use cSpell patterns

---

.github/workflows/build-process.yml

Supports #687.
Docfx recently released 2.60.0-preview.2 which is now a cross-platform .NET Global Tool. This is very exciting and allowed us to re-do the docfx-action to use the .NET SDK Ubuntu-based container which I think is going to give us really nice flexibility in the future.
This PR is to adopt our new action, though it's still in preview, to work out any issues.

Switch to new container edition for builds

---

.github/workflows/build-process.yml
docs/articles/developer-info/Packaging-the-V3-Adapter.md
docs/articles/nunit/technical-notes/nunit-internals/Framework-Api.md
docs/articles/nunit/technical-notes/usage/Engine-Parallel-Test-Execution.md
docs/articles/nunit/technical-notes/usage/Framework-Parallel-Test-Execution.md
docs/articles/nunit/writing-tests/attributes/explicit.md
docs/articles/nunit/writing-tests/attributes/testcasesource.md
docs/articles/nunit/writing-tests/attributes/testfixturesource.md

We used someone else's container action for markdown linting in our build process. If we use the markdownlint package directly, we'll have a consistent experience between our build & devcontainer tooling. Plus the container was old, and the latest markdownlint edition adds some more rules that we should address.

Markdown linting: latest tooling & accompanying fixes

---

CONTRIBUTING.md

Hopefully addresses some of @CharliePoole's concerns around the contribution process being less accessible.
* Updates CONTRIBUTING.MD to walk through using in-line editing, the traditional method, and devcontainer via Codespaces or VS Code locally
* Links to a video I recorded demoing how to do it and how it all works.

Add additional contribution content

---

docs/articles/nunit/getting-started/dotnet-core-and-dotnet-standard.md
docs/articles/nunit/running-tests/NUnitLite-Options.md
docs/articles/vs-test-adapter/AdapterV3-Release-Notes.md
docs/articles/vs-test-adapter/AdapterV4-Release-Notes.md

This will ensure the links work correctly in any built environment, since docfx converts them at build time.
Resolves #607.

Move explicit `docs.nunit.org` URLs to be relative

---

docs/articles/nunit/writing-tests/attributes/teardown.md

It was correctly pointed out in #564 that Tear down does indeed run in some circumstances even when SetUp fails.
I rephrase this in terms of a guarantee.
Resolves #564.

Update TearDown language to talk about guarantees.

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
CONTRIBUTING.md
README.md

For use when working with snippets in the devcontainer.
Resolves #705.

Devcontainer: C# extension and alias for samples

---

docs/articles/nunit/writing-tests/attributes/testcasesource.md

The class `TestCaseDataParameters` does not exist in NUnit. The https://docs.nunit.org/articles/nunit/writing-tests/TestCaseData.html page already use `TestCaseParameters`.
See also https://github.com/nunit/nunit.analyzers/issues/523#issuecomment-1439574581 for context

chore: Correct class name

---

docs/404.md

Supports #360.
Uses docfx to create a 404.html
Google pages picks up on the 404.html file and should serve it.
Once this works, I'll see if the analytics picks up on where 404 pages are resulting (I think it does), or if I need to add specific analytics script on the 404 page.

Add Custom 404 Page

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/build-process.yml
docs/docfx.json

Update docfx-action to 2.5.0 in build/codespaces

---

docs/articles/nunit/writing-tests/attributes/ignore.md

- Added missing parenthesis in Ignore Until code example.
- Added missing curly bracket in Test Syntax section.
Resolves #765

Fixed missing parenthesis and curly bracket on the Ignore attribute page

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/build-process.yml

Closes #781.
https://github.com/dotnet/docfx/pull/8934~ This doesn't work in devcontainers
https://github.com/dotnet/docfx/pull/8892

Update docfx-action to 2.8.0 (docfx v2.70.0)

---

.devcontainer/Dockerfile
.github/workflows/build-process.yml

Tested locally in a dev container. Should be fine to merge when the build passes.

Update docfx-action to 2.9.0 (with docfx 2.70.1)

---

docs/articles/nunit/getting-started/dotnet-core-and-dotnet-standard.md
docs/articles/nunit/getting-started/installation.md
docs/articles/nunit/getting-started/toc.yml
docs/articles/nunit/running-tests/NUnitLite-Runner.md

Updated the installation instructions to be up-to-date with how things are done in 2023.

Updated installation instructions

---

cSpell.json

Saw a warning in the build that the schema version was old. Adding this here; will make other adjustments as necessary if the build breaks

chore: Update cSpell.json schema version 0.1 -> 0.2

---

docs/articles/nunit/writing-tests/TestContext.md

This PR improves the documentation for the `CurrentContext` object by listing all of its properties, including clarification on only failed assertions being retained as an `AssertionResult`.

Improve documentation of the CurrentContext object

---

docs/articles/nunit/getting-started/installation.md

The last line in the Visual Studio Code section clearly belongs in the section after it, unless the author mean to say "Visual Studio Code has built-in...."
Proposing this change under the former assumption
Resolves #815

Update installation.md, fix Rider line

---

docs/articles/nunit/writing-tests/attributes/pairwise.md

Now the documentation is in the same order the output is:

Correct Pairwise output order

---

docs/articles/nunit/writing-tests/attributes/testcasesource.md
docs/articles/nunit/writing-tests/attributes/testfixturesource.md
docs/articles/nunit/writing-tests/attributes/valuesource.md

Relates to https://github.com/nunit/docs/issues/834 and https://github.com/nunit/docs/issues/756
A few quick notes about supported signatures for async method-sourced *Source attributes to start getting these into the docs. I'm only describing this as "Related to" instead of "Fixes" as I think some example method signatures could be helpful to add later.

A few points for Task<> and IAsyncEnumerable<> support on *Source attributes

---

.devcontainer/devcontainer.json
docs/articles/nunit/release-notes/breaking-changes.md
docs/articles/nunit/release-notes/framework.md
docs/articles/nunit/toc.yml

Autogenerated release notes for nunit 4.0

Update nunit 4.0 release notes

---

docs/articles/nunit/release-notes/Nunit4.0-MigrationGuide.md

I've noticed a bit of hesitation on social media about the changes to assert styles. I thought a minor wording change could help here, mostly around dropping the word "convert" in one of the headings to minimize apparent friction.
I'm unsure which of these could be preferable so I've gone with the shorter, first alternative in this PR for now:
```diff
- #### Convert Classic Assert into NUnit 4.x equivalent
+ #### Using Classic Asserts in NUnit 4.x
```
or
```diff
- #### Convert Classic Assert into NUnit 4.x equivalent
+ #### Using Classic-style Asserts in NUnit 4.x
```
@manfred-brands @SeanKilleen I know you each put a lot of work into the guide, so I'd appreciate your thoughts on this

Minor wording adjustment to migration guide

---

.github/workflows/closed-pr.yml

Was leftover from when I was deactivating them. May be causing the current error.

Remove description from deleted env

---

.github/workflows/build-process.yml

Environment deletion can be automated, but requires permissions.
So, I generated a small-scoped token for and used it as a GitHub Actions secret.
Let's see if it works. :) 🤞

Use PAT for env deletion

---

docs/articles/vs-test-adapter/Adapter-Engine-Compatibility.md

Convert header to warnings

---

docs/articles/nunit/release-notes/framework.md

Add missing framework release notes for https://github.com/nunit/nunit/issues/3043 as it had been missing the milestone at the time the release notes were generated

Add missing item to 4.0.0 framework release notes

---

docs/articles/nunit/release-notes/framework.md

Similar to PR https://github.com/nunit/docs/pull/880
Framework issue https://github.com/nunit/nunit/issues/3941 was done as part of 4.0 but was not in the milestone at the time the release notes were generated

Add nunit issue 3941 to 4.0.0 framework release notes

---

.devcontainer/Dockerfile
.github/workflows/build-process.yml
README.md
docs/articles/nunit/extending-nunit/Custom-Attributes.md

Fixes #883
The entry point `markdownlint-cli2-config` was removed in markdownlint-cli2 version 0.12.0.
See https://github.com/DavidAnson/markdownlint-cli2/blob/82c791e94c2e2ab2119437d61c722c8e0c20d6c9/CHANGELOG.md?plain=1#L11-L12
And failed build in https://github.com/nunit/nunit.analyzers/actions/runs/7596383794/job/20690026186?pr=675

chore: `markdownlint-cli2-config` is removed use `--config` flag instead

---

docs/articles/nunit/release-notes/framework.md

Similar to PR https://github.com/nunit/docs/pull/880
Framework issue https://github.com/nunit/nunit/issues/3588 was done as part of 4.0 but was open and not in the milestone at the time the release notes were generated.
Hopefully the last of the 4.0 items missing from the release notes 🙂

Add nunit issue 3588 to 4.0.0 framework release notes

---

docs/articles/nunit-engine/release-notes.md

Release notes for the console/engine is automatically added to that repo's wiki, where we don't find them. 
So, copying them for now over to the docs repo.
Later we need to figure out how to best go about doing the job only once, and then to this docs repo.

updating missing releases in console and engine release notes

---

docs/articles/nunit/running-tests/Console-Command-Line.md
docs/articles/nunit/running-tests/NUnitLite-Options.md

I ran into the issue described in https://github.com/nunit/nunit-console/issues/711.
In many shells/terminals, the semicolon in an option like `--explore:output.txt;format=cases` can be problematic.
In my case, with bash, the semicolon is parsed as a separator of commands.
So, `--explore:output.txt` is passed to nunit-console, but the `format=cases` part is separately executed by bash.
Because both of the resulting commands are valid, no warnings/errors are printed and nunit-console will write output into a file with the expected `output.txt` filename.
It made it look like nunit-console just didn't support the "format" attribute anymore.
I hope adding this mention of the semicolon in the docs will avoid some confusing/time-consuming debugging for other people.

Make readers aware of potential issue with semicolon in terminal

---

docs/articles/nunit/writing-tests/constraints/CollectionEquivalentConstraint.md
docs/articles/nunit/writing-tests/constraints/CollectionSubsetConstraint.md
docs/articles/nunit/writing-tests/constraints/CollectionSupersetConstraint.md
docs/articles/nunit/writing-tests/constraints/DictionaryContainsValueConstraint.md
docs/articles/nunit/writing-tests/constraints/SomeItemsConstraint.md

Docs follow-up on (and contingent on merge of) https://github.com/nunit/nunit/pull/4729, which fixes https://github.com/nunit/nunit/issues/4726
I filled in the missing overloads and made sure the ordering is consistent too

Add docs for custom equality generic parameter rename

---

docs/articles/nunit/release-notes/framework.md

I noticed while digging through some diffs recently that https://github.com/nunit/nunit/issues/2835 missed the milestone and missed being included in the release notes.

Add a missing item from the framework Version 4 release notes

---

docs/articles/nunit/technical-notes/usage/Debugging-Support.md
docs/articles/nunit/technical-notes/usage/toc.yml
docs/articles/vs-test-adapter/Tips-And-Tricks.md

Fix https://github.com/nunit/nunit/issues/4765
@OsirisTerje , I've added adapter notes, but cannot find suitable document under `docs\articles\nunit\technical-notes`

Document ThrowOnEachFailureUnderDebugger option

---

renovate.json

This introduces a RenovateBot custom manager.
In the `build-process.yml` file, it will look for the version in `NUNIT_VERSION_FOR_API_DOCS`, and will suggest an update for it when a new version of NUnit is published.
This ensures that our docs get PRs to stay up to date when a new version of NUnit is released.
Supports #941. Going to choose to leave it open for now because I have to merge this first before I can see if it's successful (I should see a PR generated to update to 4.1.0.

Use RenovateBot for API docs version in build

---

renovate.json

Update file match to be more precise

---

docs/articles/nunit/writing-tests/attributes/theory.md

The first sentence under the section "Theories in Generic Fixtures" didn't make sense at first, until I substituted the word "or" with the phonetically similar word "are".

Fix wording in theory.md

---

docs/articles/nunit/release-notes/Nunit4.0-MigrationGuide.md

NUnit 3.x to 4.x semi-automatic migration support

---

docs/articles/nunit/release-notes/framework.md

Back-filling this into the docs for https://github.com/nunit/nunit/issues/4632.
The milestone got missed on this one until recently.

Update framework release notes for a missed enhancement

---

docs/articles/nunit-engine/extensions/AvailableExtensions.md

Fixing command for choco install as here:
https://community.chocolatey.org/packages/nunit-extension-nunit-v2-result-writer#individual

Fixing command for choco install of nunit results v2 extension

---

docs/articles/developer-info/The-Teams.md

Added Charlie Poole as a member of core team, and the team lead of the Engine/Console team

Updated teams information with Charlie Poole entering core and engine.

---

docs/articles/nunit/release-notes/framework.md

HTML is not valid in markdown and we need to avoid it where possible.
Similarly, using tables for purely visual layout is to be avoided, especially when there are not clear columns. It cuts things off on mobile and can be detrimental to the accessibility experience.

Move table to valid markdown in release notes

---

.github/workflows/build-process.yml

Update .NET in build runner to 9.x; node to v22

---

docs/articles/nunit/writing-tests/attributes/cancelafter.md

Fix typo and links in CancelAfter documentation

---

.github/linters/.markdownlint.yml
.markdownlintrc
.vscode/settings.json
README.md

After a quick conversation with @OsirisTerje we agreed that 1) it would be helpful to auto-fix markdownlint issues in docs on save, and 2) we didn't want the line length to cause issues in linting.
So, this PR:
* Adds the auto-fix on save functionality for Codespaces (and puts the same in the readme)
* Removes the line length linting
* Leaves the Rewrap plugin so that we can still have some friendly help on line length when desired
* Leaves `"editor.rulers": [120]` in settings so that we have a visual guideline.
Closes #887

Auto-fix linting and remove line length linting

---

docs/articles/nunit/writing-tests/assertions/multiple-asserts.md
docs/snippets/Snippets.NUnit/MultipleAsserts.cs

Add documentation for EnterMultipleScope

---

.github/workflows/build-process.yml

Supports #983 by at least making it less confusing in terms of which aspects of the process are failing. This way folks can easily see that the build passed but the preview didn't.
Also the netlify preview task isn't required to pass in order to merge, so it should make that clearer too.

Separate Netlify preview into its own build task

---

docs/articles/nunit/writing-tests/constraints/DictionaryContainsKeyConstraint.md

Relates to https://github.com/nunit/nunit/issues/4981

Update DictionaryContainsKeyConstraint modifiers

---

docs/articles/nunit/writing-tests/attributes/repeat.md
docs/snippets/Snippets.NUnit/Attributes/RepeatAttributeExample.cs

Moved examples to the snippets
Added info on StopOnFailure property
Added warning on NUnit Issue 5031

Updated doc on repeat attribute
